name: CI + CD

on:
  workflow_dispatch:

jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running in Staging"
        
  Development:
    runs-on: ubuntu-latest
    environment: Development
    needs: Staging
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running in develpment"
        
  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: Development
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "Deployed in Production"
    
  
